version: "3"

services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: api-container
    build: .
    image: project-ft
    restart: always
    command: yarn debugs
    volumes:
      - ./dist:/usr/src/project-ft/dist
      - ./package.json:/usr/src/project-ft/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
